[tool.poetry]
name = "hw2robotevolution"
version = "0.1.0"
description = ""
authors = ["zamanlh <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
Box2D = "^2.3.10"
gym = "^0.18.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
